# Generated by go2rpm
%bcond_without check

# https://github.com/kubernetes/apimachinery
%global goipath         k8s.io/apimachinery
%global forgeurl        https://github.com/kubernetes/apimachinery
Version:                1.21.1
%global tag             kubernetes-1.21.1
%global distprefix      %{nil}

%gometa

%global common_description %{expand:
Scheme, typing, encoding, decoding, and conversion packages for Kubernetes and
Kubernetes-like API objects.}

%global golicenses      LICENSE
%global godocs          CONTRIBUTING.md code-of-conduct.md README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Scheme, typing, encoding, decoding, and conversion packages for Kubernetes

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/davecgh/go-spew/spew)
BuildRequires:  golang(github.com/docker/spdystream)
BuildRequires:  golang(github.com/evanphx/json-patch)
BuildRequires:  golang(github.com/gogo/protobuf/proto)
BuildRequires:  golang(github.com/gogo/protobuf/sortkeys)
BuildRequires:  golang(github.com/golang/protobuf/proto)
BuildRequires:  golang(github.com/google/go-cmp/cmp)
BuildRequires:  golang(github.com/google/gofuzz)
BuildRequires:  golang(github.com/google/uuid)
BuildRequires:  golang(github.com/googleapis/gnostic-0.4/compiler)
BuildRequires:  golang(github.com/googleapis/gnostic-0.4/openapiv2)
BuildRequires:  golang(github.com/hashicorp/golang-lru)
BuildRequires:  golang(github.com/json-iterator/go)
BuildRequires:  golang(github.com/modern-go/reflect2)
BuildRequires:  golang(github.com/mxk/go-flowrate/flowrate)
BuildRequires:  golang(github.com/spf13/pflag)
BuildRequires:  golang(golang.org/x/net/html)
BuildRequires:  golang(golang.org/x/net/html/atom)
BuildRequires:  golang(golang.org/x/net/http2)
BuildRequires:  golang(gopkg.in/inf.v0)
BuildRequires:  golang(gopkg.in/yaml.v2)
BuildRequires:  golang(k8s.io/klog)
BuildRequires:  golang(k8s.io/kube-openapi/pkg/util/proto)
BuildRequires:  golang(sigs.k8s.io/structured-merge-diff/v4/value)
BuildRequires:  golang(sigs.k8s.io/yaml)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/elazarl/goproxy)
BuildRequires:  golang(github.com/golang/groupcache/lru)
BuildRequires:  golang(github.com/stretchr/testify/assert)
BuildRequires:  golang(github.com/stretchr/testify/require)
BuildRequires:  golang(golang.org/x/net/websocket)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep
sed -i "s|sigs.k8s.io/structured-merge-diff/v3|sigs.k8s.io/structured-merge-diff/v4|" $(find . -type f -iname "*.go")
sed -i "s|github.com/googleapis/gnostic/OpenAPIv2|github.com/googleapis/gnostic/openapiv2|" $(find . -type f -iname "*.go")
sed -i 's|github.com/googleapis/gnostic|github.com/googleapis/gnostic-0.4|' $(find . -iname "*.go" -type f)

%install
%gopkginstall

%if %{with check}
%check
%gocheck -d pkg/util/httpstream/spdy -d pkg/util/proxy
%endif

%gopkgfiles

%changelog
* Tue May 25 2021 Major Hayden <major@mhtx.net> - 1.21.1-1
- Update to 1.21.1

* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 1.18.9-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Tue Sep 29 20:43:53 CEST 2020 Robert-André Mauchin <zebob.m@gmail.com> - 1.18.9-1
- Update to 1.18.9

* Wed Aug 19 18:24:00 CEST 2020 Robert-André Mauchin <zebob.m@gmail.com> - 1.18.3-4
- Use gnostic compat package

* Sat Aug 01 2020 Fedora Release Engineering <releng@fedoraproject.org> - 1.18.3-3
- Second attempt - Rebuilt for
  https://fedoraproject.org/wiki/Fedora_33_Mass_Rebuild

* Mon Jul 27 2020 Fedora Release Engineering <releng@fedoraproject.org> - 1.18.3-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_33_Mass_Rebuild

* Sun Jun 14 18:24:27 CEST 2020 Robert-André Mauchin <zebob.m@gmail.com> - 1.18.3-1
- Update to 1.18.3

* Sun Apr 12 21:19:10 CEST 2020 Robert-André Mauchin <zebob.m@gmail.com> - 1.18.1-1
- Update to 1.18.1

* Wed Feb 05 18:24:51 CET 2020 Robert-André Mauchin <zebob.m@gmail.com> - 1.17.2-1
- Update to 1.17.2

* Wed Jan 29 2020 Fedora Release Engineering <releng@fedoraproject.org> - 1.15.0-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Thu Jul 25 2019 Fedora Release Engineering <releng@fedoraproject.org> - 1.15.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Sat Jul 06 16:21:53 CEST 2019 Robert-André Mauchin <zebob.m@gmail.com> - 1.15.0-1
- Release 1.15.0

* Thu May 09 15:26:09 CEST 2019 Robert-André Mauchin <zebob.m@gmail.com> - 1.13.7-1.beta.0
- Initial package
